baseurl = "https://xuzhijvn.github.io/"
title = "å”¯æœ‰å…‰å¤´ğŸ‘´ğŸ»æ‰èƒ½å˜å¼ºğŸ’ª"
theme = "hugo-theme-bootstrap"
copyright = "Copyright Â© 2016-{year} Razon Yang. All Rights Reserved."

defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = true

enableRobotsTXT = true

enableEmoji = true

[blackfriday]
  hrefTargetBlank = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup.goldmark.renderer]
unsafe= true
