author = "Tony Xu"
brand = "唯有光頭才能變強"
palette = "indigo"
description = "Web 开发技术博客"

mainSections = ["posts"]

recentPostCount = 5
featuredPostCount = 5

# featuredPostCount = 10 # The number of featured posts shown in sidebar.
# recentPostCount = 10 # The number of recent posts shown in sidebar.
# relatedPostCount = 10 # The number of related posts.
categoryCount = 100 # The number of categories shown in sidebar.
tagCount = 100 # The number of tags shown in sidebar.
seriesCount = 100 # The number of series shown in sidebar.
tocWordCount = 10
titleCase = false

[beian]
  no = "粤公网安备44040302000341号"
  link = "http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=44040302000341"
  icpNo = "粤ICP备20043980号"
  icpLink = "http://beian.miit.gov.cn/"

[share]
  addThis = "ra-5fb19b4fde14befc"

[reward]
  alipay = "images/reward/alipay.png"
  wechat = "images/reward/wechat.png"

[post]
  # excerpt = "description"
  excerptMaxLength = 120
